version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: logitrack_postgres
    restart: always
    environment:
      POSTGRES_USER: logiuser
      POSTGRES_PASSWORD: logipass
      POSTGRES_DB: logitrack
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
